fieldLayouts:
  2995097b-9b10-49db-a8bd-c9844d6a68d1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0310efe3-12df-418c-a30b-121cf8981bf8 # Contact Card Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2305655f-aa31-4aa2-a67f-f9ccdb6cada7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 78139d94-7a12-4f02-a8e4-8608aee5ea55 # Contact Card Role
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2db508ca-0e14-49dd-9cec-5aa4009a1ace
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e95f6249-f44b-4730-9462-fb2831e7a5fa # Contact Card Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f15b38d3-824c-41d9-8cfc-467d86baa0d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 57477ea0-4de8-4b6a-8864-f6afc2f25a7c # Contact Card Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2abc013-482b-419f-b309-a8ae7a82a0f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4feacf6-0a3c-4856-a36f-cd816263384d # Contact Card Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebf1ee32-fcaa-4ae0-9de6-25d7d5733919
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6e27606c-497d-4c34-9a13-3aaa8c37e93b
        userCondition: null
handle: contactCard
name: 'Contact Card'
sortOrder: 1
