fieldLayouts:
  9db3d397-08f0-4aeb-8747-e96a7a2b9a7d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fc71a9bd-c2ca-4026-bec7-e91ac7d0c96b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2b4a9fe1-30b9-46eb-bf48-cf76750cbc76 # Heroine Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95231b53-3f1a-4e43-8f5b-d7c483c3d3cf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e286f9b7-986e-4d00-a407-41b8c313cfa7 # Heroine Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4f7dab0-4a27-4ec1-88c7-78ef5b90e207
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: defa5ab6-258a-483a-8b57-a839b86289af
        userCondition: null
handle: aboutUs
hasTitleField: true
name: 'About Us'
section: 1e53762a-6675-426a-9783-3793bdd16929 # About Us
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
