fieldLayouts:
  17cc3486-9bf3-43cb-a76c-53e44329528e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7fda213f-2987-40cf-9b80-b58d6bdf3897
            warning: null
            width: 100
        name: Content
        uid: 54520c51-3799-4a0e-9705-2c84a0d4b541
handle: dataPrivacy
hasTitleField: false
name: 'Data Privacy'
section: cf05b8dd-8dfa-47ae-a86d-e19e315bd668 # Data Privacy
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
