fieldLayouts:
  f03ba3c7-7085-47b9-9adb-7704350189c9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 46c1b2a1-cd48-4588-a279-b3a08c4d1526
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 81f1ea57-8f3f-4a92-aa27-52460033d593 # Hero Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 095fd61e-5ed3-4592-9c98-f67671c23121
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 01907158-7087-433f-a781-b6f78c024142 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cefaa6ce-43c4-4b38-bca6-60c071620b94
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 611a3848-5826-4e32-bb17-992fd9937ba8 # Hero Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec4dcc81-7899-400e-af8f-f489ef040db8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 27ac0dfa-7829-4c20-a126-ba9e1a725fad
        userCondition: null
handle: hero
hasTitleField: false
name: Hero
section: b6338b26-4732-4e95-bd2f-d6ce9da766ca # Hero
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
