fieldLayouts:
  31a64a2c-3388-4d45-b0ca-e05b08c96293:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4677813c-446c-404a-8e59-f84abc05ffe5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d2441ac-0860-4f07-b558-d5b6ce38e210 # Intro Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 390cc49e-d5de-4d1b-874e-8264a8bcd473
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b775433a-4ff9-4a89-8266-7cc268cdd27d # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a767dd5-6e1d-4dd5-9c10-849e88c9cdc8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0afac1c9-dae5-4072-8a23-79cbd3187e85 # Intro Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b8620db-2928-4d78-9566-4353da49ae24
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 33a9da36-aa76-4e84-b755-41c86a47b2e5
        userCondition: null
handle: intro
hasTitleField: false
name: Intro
section: 9b20354d-0990-4f36-bd10-d236944601e3 # Intro
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
