fieldLayouts:
  13971a86-ba0a-4c56-a2c6-35505dc88558:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 19d60be7-079a-4ffc-b168-93afdb8abb72
            warning: null
            width: 100
        name: Content
        uid: a0e41219-97d9-4074-8962-33c80bfd16f1
handle: invesmentAdvisory
hasTitleField: true
name: 'Investment Advisory'
section: f9dc201a-1d70-41de-addd-45fd5fafb195 # Investment Advisory
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
