fieldLayouts:
  13971a86-ba0a-4c56-a2c6-35505dc88558:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 19d60be7-079a-4ffc-b168-93afdb8abb72
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2b4a9fe1-30b9-46eb-bf48-cf76750cbc76 # Heroine Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a2fd149-feeb-424e-844d-4231558a0bd9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e286f9b7-986e-4d00-a407-41b8c313cfa7 # Heroine Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f41e5418-97d9-4d16-afb0-e932fe423ae6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a0e41219-97d9-4074-8962-33c80bfd16f1
        userCondition: null
handle: invesmentAdvisory
hasTitleField: true
name: 'Investment Advisory'
section: f9dc201a-1d70-41de-addd-45fd5fafb195 # Investment Advisory
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
