fieldLayouts:
  e88ad07d-b69f-453b-87bf-0694be07783e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 55e50ec9-395b-4b43-9c64-5354f7570daf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2b4a9fe1-30b9-46eb-bf48-cf76750cbc76 # Heroine Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 069333ec-1416-4496-8ded-71ad56acffc7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e286f9b7-986e-4d00-a407-41b8c313cfa7 # Heroine Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc1e9624-73c3-4132-856d-b59cdf12be35
            userCondition: null
            warning: null
            width: 100
        name: Heroine
        uid: d44bd344-8c52-449b-8ecc-4d8eef5151da
        userCondition: null
handle: retirementSolutions
hasTitleField: false
name: 'Retirement Solutions'
section: 9f90e5bc-9157-4526-8dde-681edb929c58 # Retirement Solutions
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
