fieldLayouts:
  3d39b355-87df-456d-b3df-9347e402ae0b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: db61baad-2cee-4ef4-a4f8-86b0099b481d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7d880355-fde3-4340-8cd4-222abc47e419 # Services Overview Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9321ff1-e8c3-4929-b252-6e3e33ea24e5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 07849dff-6914-472d-aa66-45e4fd5159c7
        userCondition: null
handle: servicesOverview
hasTitleField: false
name: 'Services Overview'
section: fdb0e106-0211-4916-9994-786896c7b8ef # Services Overview
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
