field: f77929a1-2499-4ef1-8c31-545e3d547cb4 # Legal Information Item
fieldLayouts:
  5e4c52e9-4139-47b2-bc3f-1f802f033e57:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f303fc4f-2747-4682-8b40-3259a9821000 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb22b5f7-6dfa-415b-a4d3-fc11f5ec5bf3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e530ad62-1aef-408b-a02f-03b2931c057f # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edbc474d-9356-4dce-950c-fb9b1d3012bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 44525f07-fb87-4d8a-a9a9-875b41bba211 # Key
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4668b26c-2dd2-4897-a67e-5fad3b22ed77
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8cc96d6b-e067-4a81-87a3-52029dc0b780
        userCondition: null
fields:
  44525f07-fb87-4d8a-a9a9-875b41bba211: # Key
    columnSuffix: efyhjctm
    contentColumnType: text
    fieldGroup: null
    handle: key
    instructions: null
    name: Key
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e530ad62-1aef-408b-a02f-03b2931c057f: # Text
    columnSuffix: fjdaqaao
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f303fc4f-2747-4682-8b40-3259a9821000: # Heading
    columnSuffix: xtkdhitn
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: paragraph
name: Paragraph
sortOrder: 1
