columnSuffix: null
contentColumnType: string
fieldGroup: 19cff30f-a1a3-4caa-a7dc-c4cdb59d70db # About Us
handle: aboutUsMember
instructions: null
name: 'About Us Member'
searchable: false
settings:
  contentTable: '{{%matrixcontent_aboutusmember}}'
  maxBlocks: null
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
