columnSuffix: bbmdlksq
contentColumnType: text
fieldGroup: 64e36b03-32f3-4b82-b976-a3eaef3f8705 # Address
handle: addressCountry
instructions: null
name: 'Address Country'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
