columnSuffix: hepjyjfe
contentColumnType: text
fieldGroup: 2a514103-f593-40e7-9f8a-cd240124bce3 # Contact Infos
handle: contactInfosTeaserIntro
instructions: null
name: 'Contact Infos Teaser Intro'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
