columnSuffix: peojzezs
contentColumnType: text
fieldGroup: d6fab119-06a5-434f-bab0-8836d0bebef0 # Course Intro
handle: courseIntroInfoPeaker
instructions: null
name: 'Course Intro Info Peaker'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
