columnSuffix: uppxkxpo
contentColumnType: text
fieldGroup: d6fab119-06a5-434f-bab0-8836d0bebef0 # Course-Intro
handle: courseIntroInfoButtonHref
instructions: null
name: 'Course Intro Info  Button Href'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
