columnSuffix: yzyrvclj
contentColumnType: text
fieldGroup: d6fab119-06a5-434f-bab0-8836d0bebef0 # Course Intro
handle: courseIntroInfoTeaser
instructions: null
name: 'Course Intro Info Teaser'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
