columnSuffix: biwipqfc
contentColumnType: text
fieldGroup: 86baf79e-9a0e-4654-9494-66d604f2a4d4 # Heroine
handle: heroineHeading
instructions: null
name: 'Heroine Heading'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
