columnSuffix: rzbtrirq
contentColumnType: text
fieldGroup: dbd572db-9982-4f04-a380-7ede02769ab3 # Intro
handle: introText
instructions: null
name: 'Intro Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
