columnSuffix: yfkwgcll
contentColumnType: text
fieldGroup: c2f319a5-193f-4bcf-8906-fbc7cf6f6a5d # Teaser
handle: teaserText
instructions: null
name: 'Teaser Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
