defaultPlacement: end
enableVersioning: true
handle: courseIntro
name: 'Course Intro'
propagationMethod: all
siteSettings:
  ac664f09-a9af-40d3-a60f-889403d18d91: # kr-consulting
    enabledByDefault: true
    hasUrls: true
    template: course-intro/_entry
    uriFormat: course-intro
type: single
