defaultPlacement: end
enableVersioning: true
handle: hero
name: Hero
propagationMethod: all
siteSettings:
  ac664f09-a9af-40d3-a60f-889403d18d91: # kr-consulting
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
