defaultPlacement: end
enableVersioning: true
handle: login
name: Login
propagationMethod: all
siteSettings:
  ac664f09-a9af-40d3-a60f-889403d18d91: # kr-consulting
    enabledByDefault: true
    hasUrls: true
    template: 05_pages/login.twig
    uriFormat: '{slug}'
type: single
