defaultPlacement: end
enableVersioning: true
handle: retirementSolutions
name: 'Retirement Solutions'
propagationMethod: all
siteSettings:
  ac664f09-a9af-40d3-a60f-889403d18d91: # kr-consulting
    enabledByDefault: true
    hasUrls: true
    template: 05_pages/retirement-solutions.twig
    uriFormat: '{slug}'
type: single
