defaultPlacement: end
enableVersioning: true
handle: services
name: Services
propagationMethod: all
siteSettings:
  ac664f09-a9af-40d3-a60f-889403d18d91: # kr-consulting
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: f81d1dab-23e2-4e17-8cf4-6f3250c925dd
type: structure
