dateModified: 1659877402
elementSources:
  craft\elements\Asset:
    -
      disabled: false
      key: 'volume:0b60c779-bb71-4367-82ad-f7f1db120c6c' # Services
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
    -
      disabled: false
      key: 'volume:c03fd4f8-9d29-48e8-871a-0640a9b29a06' # General
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
    -
      disabled: false
      key: 'volume:75c6b6cf-12b2-45c1-a198-a12c9f0fb5a5' # Avatars
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
    -
      disabled: false
      key: 'folder:1e509573-0358-478f-8e2c-10a8582f981c'
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
    -
      disabled: false
      key: 'volume:9e8eb58d-2f95-4250-afb1-6107732b2334' # Logos
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
  craft\elements\Entry:
    -
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      disabled: false
      key: singles
      tableAttributes:
        - link
        - slug
        - type
      type: native
    -
      heading: ''
      type: heading
    -
      disabled: false
      key: 'section:6ef04a00-5ae7-4cb6-a2b7-1d1ad0acf651' # Services
      tableAttributes:
        - postDate
        - expiryDate
        - link
        - 'field:7fe5694e-3563-4eca-9971-e73e8cc0f0f1' # Services ID
        - 'field:6384771e-f281-43f1-b837-ba8472992e03' # Services Label
      type: native
email:
  fromEmail: tools@haaswebsolutions.io
  fromName: kr-consulting
  transportType: craft\mail\transportadapters\Sendmail
fs:
  avatars:
    hasUrls: true
    name: Avatars
    settings:
      path: ./uploads/avatars
    type: craft\fs\Local
    url: /uploads/avatars
  general:
    hasUrls: true
    name: General
    settings:
      path: ./uploads/general
    type: craft\fs\Local
    url: /uploads/general
  logos:
    hasUrls: true
    name: Logos
    settings:
      path: ./uploads/logos
    type: craft\fs\Local
    url: /uploads/logos
  services:
    hasUrls: true
    name: Services
    settings:
      path: ./uploads/services
    type: craft\fs\Local
    url: /uploads/services
meta:
  __names__:
    0a7888cb-4004-44b3-841e-522126ec3c16: 'Contact Infos Location Button Text' # Contact Infos Location Button Text
    0afac1c9-dae5-4072-8a23-79cbd3187e85: 'Intro Image' # Intro Image
    0b60c779-bb71-4367-82ad-f7f1db120c6c: Services # Services
    0d2441ac-0860-4f07-b558-d5b6ce38e210: 'Intro Heading' # Intro Heading
    0e8b9745-1a76-4aa6-b2f1-f72225252c2c: Common # Common
    0e9eb790-792d-45ae-b92c-a0e5ef0c3a54: Teaser # Teaser
    0e183b6a-831b-4ec6-832a-8a3710434247: 'Course Intro Info Heading ' # Course Intro Info Heading 
    1bf79331-40d8-4de6-b642-5f86dced3327: 'Services Overview' # Services Overview
    1e53762a-6675-426a-9783-3793bdd16929: 'About Us' # About Us
    2a514103-f593-40e7-9f8a-cd240124bce3: 'Contact Infos' # Contact Infos
    2b4a9fe1-30b9-46eb-bf48-cf76750cbc76: 'Heroine Heading' # Heroine Heading
    02de833d-159e-4685-b65a-206aab579554: 'Address Street' # Address Street
    3b103574-a626-48b3-8a51-7308dc958912: 'Services Teaser' # Services Teaser
    3de39d90-3539-4e32-a20d-4fac31dc12aa: Stats # Stats
    3e0400fb-63d8-40fc-a7ee-b7b8c58befe2: 'CTA Button Text' # CTA Button Text
    4ab10882-1b74-4e5b-a038-afbd75a302f8: 'Contact Infos Location Image' # Contact Infos Location Image
    4b79b7f0-fba0-4475-9767-de9856691ef0: 'Address City' # Address City
    4c1b1937-b330-4172-b6b4-fe7f3bc8ebde: 'Meta Page Description' # Meta Page Description
    5a72f800-8d3a-401e-a06a-58040bae612a: Stats # Stats
    05abef9a-1f12-4388-9f90-86f28757b001: 'Legal Information Intro' # Legal Information Intro
    5c3c0987-628c-42a0-8113-d9ad4ed0b881: 'Hero Button Href' # Hero Button Href
    5e9517dd-12e4-432b-8d84-b04f4723109e: href # href
    5ebc446b-1d16-47b3-890a-35c338268fa6: Imprint # Imprint
    5f7cf41c-a93e-4f90-a1cc-c496f7a0fb82: 'Statement Full Name' # Statement Full Name
    6ae3604a-a79b-4d64-9f7c-069256175426: CTA # CTA
    6b3e7a5e-7a56-49a6-80f8-fca6b548d8bb: 'Contact Infos Teaser Button Text' # Contact Infos Teaser Button Text
    6b177a7b-e7bf-48bb-ae7b-4160f6bf4d7d: 'Course Intro Info Peaker' # Course Intro Info Peaker
    06be8ea9-6497-4d58-9cbc-4059c1c50b06: 'Contact Infos Location Heading' # Contact Infos Location Heading
    6ef04a00-5ae7-4cb6-a2b7-1d1ad0acf651: Services # Services
    6f9e4970-bcc2-4757-8a80-ca6ae4106ca6: 'Legal Information' # Legal Information
    6fd6f5f4-2ae1-451d-9f3a-a377f8123232: 'Course Intro Article Label' # Course Intro Article Label
    7beca399-c10a-42c8-90d9-611b7fd09df4: 'Connection LinkedIn' # Connection LinkedIn
    7d880355-fde3-4340-8cd4-222abc47e419: 'Services Overview Heading' # Services Overview Heading
    7e98ac50-cfc1-42c5-901f-5a01378be6c0: 'Teaser Text' # Teaser Text
    7fe5694e-3563-4eca-9971-e73e8cc0f0f1: 'Services ID' # Services ID
    8c774afe-67f9-446b-b7ca-9d1309c17f59: 'Address Company' # Address Company
    8ca4ffd7-e0ec-486c-ae72-e40e733bc421: button # button
    8cfa3bff-513c-423a-b99d-8aea13bc9592: 'Course Intro Article Image' # Course Intro Article Image
    8d6d168f-afc4-40b0-b85e-a0c9819067e8: Contact # Contact
    8d9fb8fc-aa34-42cb-98bc-97228160016c: 'Investment Advisory' # Investment Advisory
    09b0178f-ea85-4605-9a03-d578f41e6721: 'Connection Phone' # Connection Phone
    9b6e4be8-876c-4971-95a7-d952bac89124: text # text
    9b20354d-0990-4f36-bd10-d236944601e3: Intro # Intro
    9ca332d8-ae84-4fd6-a910-86840be2a2ad: 'Course Intro Quote Text ' # Course Intro Quote Text 
    9d822dff-c1c0-4211-933b-31fb7ad99fac: Hero # Hero
    9e8eb58d-2f95-4250-afb1-6107732b2334: Logos # Logos
    9f90e5bc-9157-4526-8dde-681edb929c58: 'Retirement Solutions' # Retirement Solutions
    010edfe8-bf11-404d-ac0e-d609cb946713: CTA # CTA
    11a04655-b47f-4799-821e-6d092d9f1fc4: Statement # Statement
    19cff30f-a1a3-4caa-a7dc-c4cdb59d70db: 'About Us' # About Us
    23da331f-4f31-4d9e-8fdc-0ff080eba556: Address # Address
    24d6a6c1-e3ba-4502-8202-9046cda01144: 'Stats Counters' # Stats Counters
    26c4a3d0-6e18-40fb-a36d-253b9ff5ea5b: Statement # Statement
    47e94b3a-30ca-480e-aade-3be1b448c694: 'Data Privacy' # Data Privacy
    47eb7355-1057-4fe3-a2fe-b912bceca812: Testimonials # Testimonials
    63ab7bb9-d043-4d70-b513-c1bd9d75d685: 'Teaser Image' # Teaser Image
    64e36b03-32f3-4b82-b976-a3eaef3f8705: Address # Address
    69f52402-22cf-4960-a42a-b404ccea0405: 'Stats Button Text' # Stats Button Text
    71b88c97-dd6f-493c-a1d7-f2f6761c3afa: Connection # Connection
    71f2cf7c-d1fb-437b-a254-5dc7597483b3: 'Contact Card' # Contact Card
    75b05fff-759a-42c7-9992-838ba424e9b2: 'Contact Infos' # Contact Infos
    75c6b6cf-12b2-45c1-a198-a12c9f0fb5a5: Avatars # Avatars
    77f88702-2981-4e43-9963-965cd0f6bcc8: 'Course Intro Long Copy Text ' # Course Intro Long Copy Text 
    79d9bae6-9855-4997-b283-75914ab58005: Image # Image
    81f1ea57-8f3f-4a92-aa27-52460033d593: 'Hero Heading' # Hero Heading
    83b94ccf-594c-43b3-a184-dd9ac3538c9e: 'Address Country' # Address Country
    84babe93-8199-4bb0-8db8-7586bbc5e99c: Intro # Intro
    86baf79e-9a0e-4654-9494-66d604f2a4d4: Heroine # Heroine
    93a03ac3-5065-4a87-9a41-5fe7ccc9fd56: Image # Image
    103d8c1e-9798-44c8-908e-bfdfd085f980: 'Team Member Persona' # Team Member Persona
    146a4478-2537-438c-acbf-11cd3bf2bfa4: Hero # Hero
    0310efe3-12df-418c-a30b-121cf8981bf8: 'Contact Card Name' # Contact Card Name
    380c6cec-01c4-4ff5-b650-59bbb0b042b9: 'Team Member' # Team Member
    465ad94a-6ff0-4776-aec3-1a8d9c28d177: Start # Start
    505b5f6b-5951-4484-9ced-7f3f61abc5d9: Auth # Auth
    525e2697-fcdb-4800-8957-4e5199799947: Email # Email
    535b41e8-932f-49eb-80e0-a57aad52a713: Teaser # Teaser
    558dd3f0-e975-4199-aa7b-34620d3d8cb8: 'Connection Email' # Connection Email
    562f5c5d-c13d-420a-8b0d-ced4ff3d6d97: Role # Role
    567b3a46-9655-43df-8e0d-02a52454e459: 'About Us' # About Us
    611a3848-5826-4e32-bb17-992fd9937ba8: 'Hero Button Text' # Hero Button Text
    0622be8b-b30f-4d45-8e51-c0449d675572: 'Meta Page Title' # Meta Page Title
    859fe36b-3d09-4575-90a8-7a8df52896ee: Introduction # Introduction
    967ce7fc-82b0-4640-b4fc-88a245b7585e: 'Course Intro Info  Button Text' # Course Intro Info  Button Text
    1085dbf3-de89-4fa4-89bd-3152f254c3f5: Testimonials # Testimonials
    1603d4ed-dff5-40eb-8f99-db85545a375e: Start # Start
    1996da9d-6afd-485e-9520-e734f9bef432: 'Services Long Copy' # Services Long Copy
    2335bc14-e769-484f-9f4f-9dc2f14e9db3: Services # Services
    5233c6b4-1d84-492e-9c52-50a05132f5d6: 'Contact Infos Location Button Href' # Contact Infos Location Button Href
    5797b8b9-3f5f-4ea9-8bd6-80f9e56e761e: 'Retirement Solutions' # Retirement Solutions
    6388ff27-c184-4c62-b869-98558bba4d29: 'Contact Infos Teaser Button Href' # Contact Infos Teaser Button Href
    44525f07-fb87-4d8a-a9a9-875b41bba211: Key # Key
    57477ea0-4de8-4b6a-8864-f6afc2f25a7c: 'Contact Card Phone' # Contact Card Phone
    78139d94-7a12-4f02-a8e4-8608aee5ea55: 'Contact Card Role' # Contact Card Role
    78967eb2-4573-48b8-830b-07fc6954c961: 'Teaser Heading' # Teaser Heading
    476265c7-1460-4f45-bfa0-b3fc7be50365: 'Team Member' # Team Member
    672102ad-6fcd-499c-be23-64c8512e979f: 'Team Member' # Team Member
    01907158-7087-433f-a781-b6f78c024142: 'Hero Image' # Hero Image
    4238344f-04f7-4d53-93f6-bdc74afc27b6: Href # Href
    6384771e-f281-43f1-b837-ba8472992e03: 'Services Label' # Services Label
    06591078-9481-42e1-a081-4b0684eb111b: 'Course Intro Info  List' # Course Intro Info  List
    9981532a-4d9a-4060-bacf-c0c4959b6d85: 'Course Intro Info  Text' # Course Intro Info  Text
    51615717-e499-40ee-93b5-35714cad533e: 'Course Intro Info  Button Href' # Course Intro Info  Button Href
    68473838-5b99-491d-b305-d7d0b6b2c1ac: 'Course Intro Article Text' # Course Intro Article Text
    86474971-bcf9-4931-b7e1-67ca6accab6e: List # List
    a8a54faf-f815-4b38-80ee-c66acca0a063: Contact # Contact
    a81b2519-de8d-404a-bff8-bcc3402ad870: Default # Default
    a806e5c0-2f5c-4d8d-99f0-0699693bed75: Paragraph # Paragraph
    a5530e38-a5e3-4672-afb8-7890d820c586: Stats # Stats
    ab59ddba-c09b-4532-b5cd-f6592b6d237f: Text # Text
    abb7c8e9-a3e2-4c0d-a2f4-23606f8a06e2: Contact # Contact
    ac664f09-a9af-40d3-a60f-889403d18d91: kr-consulting # kr-consulting
    aea1317d-1e20-4ed7-9ff3-2aa3adc44925: 'Stats Peaker' # Stats Peaker
    af78bb5f-d02a-42d9-b97f-9aa6b4c077fd: 'Stats Button Href' # Stats Button Href
    b577bd63-5d61-4855-bc46-c9b942083cf8: amount # amount
    b645bed4-42c3-4a07-adae-f918e4d05e24: 'Course Intro Long Copy Heading' # Course Intro Long Copy Heading
    b6338b26-4732-4e95-bd2f-d6ce9da766ca: Hero # Hero
    b27818e1-617f-4ed9-96a9-8b5210a2c172: Role # Role
    b775433a-4ff9-4a89-8266-7cc268cdd27d: 'Intro Text' # Intro Text
    ba58fc37-be30-4b99-a88d-7f4d9e94e73d: kr-consulting # kr-consulting
    bb3e5a39-f478-4cee-8529-310753cf10ba: 'Statement Text' # Statement Text
    bdc004e6-236b-4444-a1c9-8e8cfbdcc67c: Imprint # Imprint
    be44ff42-29c5-445b-be33-efb43b545cd0: 'CTA Heading' # CTA Heading
    be65d477-82c3-4ed6-bd1b-fbdb3916edac: 'Contact Card' # Contact Card
    bfce0724-7450-4161-8f99-dd9cf314f36e: 'Statement Image' # Statement Image
    c03fd4f8-9d29-48e8-871a-0640a9b29a06: General # General
    c2f319a5-193f-4bcf-8906-fbc7cf6f6a5d: Teaser # Teaser
    c7ba05f6-a7e8-4156-8e13-4b8a2e21a521: 'Full Name' # Full Name
    c9db1098-8537-4bff-b067-43e0df422abb: Testimonials # Testimonials
    c34dedb5-ab5a-48f3-b616-9f0aecd4d1c4: Reference # Reference
    c67b9470-1c53-4717-8383-253fbb3fec17: 'Services Overview' # Services Overview
    c157b61b-db87-471f-8609-c7f60ecf7283: Auth # Auth
    cf0c14ba-cc45-4b47-bdf2-24ae9f3fd86a: 'Image Alt Tag' # Image Alt Tag
    cf05b8dd-8dfa-47ae-a86d-e19e315bd668: 'Data Privacy' # Data Privacy
    cff01372-6ccb-42ee-b138-9e3a762fb047: 'Full Name' # Full Name
    d093d66f-bf5f-47bf-bc17-7e00f590d105: 'Contact Infos Teaser Contact Phone' # Contact Infos Teaser Contact Phone
    d4e50b84-fa6a-413b-b46f-034a989ec557: Statement # Statement
    d4feacf6-0a3c-4856-a36f-cd816263384d: 'Contact Card Image' # Contact Card Image
    d5b0b14b-5e0d-43e7-bb64-da295724ba6e: 'Legal Information' # Legal Information
    d6ade586-96dd-4523-903d-924c4fe7df63: 'Course Intro Info Image' # Course Intro Info Image
    d6fab119-06a5-434f-bab0-8836d0bebef0: 'Course Intro' # Course Intro
    d8f9a01c-3729-4a9d-838c-aaae7fae2bfe: 'Course Intro Article Outro' # Course Intro Article Outro
    d9ad9415-402b-41ed-a090-ab904bfea86b: 'Contact Infos Teaser Intro' # Contact Infos Teaser Intro
    d823a91c-5e63-4e68-9eb0-93d775259750: 'Services Image' # Services Image
    d924cbf3-1486-4fbf-ad4a-a62d6cab5263: 'Legal Information' # Legal Information
    d2481310-b317-4bb2-8863-d25fdae20952: 'Course Intro' # Course Intro
    dace2c28-14d6-44d9-bdb5-c219839745d7: 'Services Short Copy' # Services Short Copy
    dbd572db-9982-4f04-a380-7ede02769ab3: Intro # Intro
    df5fbac6-796e-4d60-8db8-173325a9d555: CTA # CTA
    dfc00c2f-8e40-41cf-8181-3df7d8cd37ca: 'Teaser Button Text' # Teaser Button Text
    dfed0f48-8e31-47d3-a4f9-bc0c00a21ee0: 'Course Intro' # Course Intro
    e01f2cd6-6f33-4599-ab41-3d7481c412eb: 'Stats Heading' # Stats Heading
    e0413374-10dc-4f2d-904c-29f083e5b4a0: 'Address Building' # Address Building
    e06ef36f-23bb-444d-a831-4c566b500a47: 'Contact Infos' # Contact Infos
    e4e357ab-0179-4c12-a820-364727587b32: Counter # Counter
    e7ce083a-c963-4214-9fa8-31b6c05ec30f: 'Course Intro Article Heading' # Course Intro Article Heading
    e48a7320-f8b9-4ab1-b877-7b9c3bcd9b7a: 'Teaser Button Href' # Teaser Button Href
    e66e9dbe-8ea7-4e6a-9d54-712031a2d2a7: Meta # Meta
    e95f6249-f44b-4730-9462-fb2831e7a5fa: 'Contact Card Email' # Contact Card Email
    e286f9b7-986e-4d00-a407-41b8c313cfa7: 'Heroine Text' # Heroine Text
    e530ad62-1aef-408b-a02f-03b2931c057f: Text # Text
    e684dceb-67da-4d43-a347-968720ed01d8: 'Legal Information Heading' # Legal Information Heading
    e8438c19-b6ae-4ad5-b06e-8e132c4ebd3c: Button # Button
    ed56c4b6-5401-43d7-931b-7f80f482366b: Text # Text
    eeada128-dc74-4253-8a77-f784c19c2fe7: 'Course Intro Quote Image' # Course Intro Quote Image
    f0ebffef-9df5-4d56-b7f4-799aea188304: Connection # Connection
    f02756b0-2a21-4a86-a44f-d8b2b9cb67af: Image # Image
    f6c273e6-1de9-44f8-964e-74d5586d58cd: 'Services Heading' # Services Heading
    f9dc201a-1d70-41de-addd-45fd5fafb195: 'Investment Advisory' # Investment Advisory
    f79b0cf6-11fc-4478-b1c3-0cec66339830: Text # Text
    f303fc4f-2747-4682-8b40-3259a9821000: Heading # Heading
    f989ecb4-faa8-4859-9890-1f9f818af555: Label # Label
    f77929a1-2499-4ef1-8c31-545e3d547cb4: 'Legal Information Item' # Legal Information Item
    f801348c-e2d6-42fe-ada9-e25d66e99e0d: Persona # Persona
    fb774718-6b6d-4033-8391-c1e5225d7442: 'CTA Button Href' # CTA Button Href
    fd65c4ec-0039-4c4e-b49c-3627453a832f: 'Contact Infos Teaser Contact Email' # Contact Infos Teaser Contact Email
    fdb0e106-0211-4916-9994-786896c7b8ef: 'Services Overview' # Services Overview
    ff056591-0e52-4d6d-91d6-5cc299d11ab6: 'Testimonials Reference' # Testimonials Reference
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: kr-consulting
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
