dateModified: 1657813113
elementSources:
  craft\elements\Entry:
    -
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      disabled: false
      key: singles
      tableAttributes:
        - link
        - slug
      type: native
    -
      heading: Navigation
      type: heading
email:
  fromEmail: tools@haaswebsolutions.io
  fromName: kr-consulting
  transportType: craft\mail\transportadapters\Sendmail
fs:
  general:
    hasUrls: true
    name: General
    settings:
      path: ./uploads/general
    type: craft\fs\Local
    url: ./uploads/general
  services:
    hasUrls: true
    name: Services
    settings:
      path: ./uploads/services
    type: craft\fs\Local
    url: ./uploads/services
meta:
  __names__:
    0b60c779-bb71-4367-82ad-f7f1db120c6c: Services # Services
    0d2441ac-0860-4f07-b558-d5b6ce38e210: 'Intro Heading' # Intro Heading
    0e8b9745-1a76-4aa6-b2f1-f72225252c2c: Common # Common
    0e9eb790-792d-45ae-b92c-a0e5ef0c3a54: Teaser # Teaser
    0e183b6a-831b-4ec6-832a-8a3710434247: 'Course Intro Info Heading ' # Course Intro Info Heading 
    1e53762a-6675-426a-9783-3793bdd16929: 'About Us' # About Us
    2b4a9fe1-30b9-46eb-bf48-cf76750cbc76: 'Heroine Heading' # Heroine Heading
    3b103574-a626-48b3-8a51-7308dc958912: 'Services Teaser' # Services Teaser
    3de39d90-3539-4e32-a20d-4fac31dc12aa: Stats # Stats
    3e0400fb-63d8-40fc-a7ee-b7b8c58befe2: 'CTA Button Text' # CTA Button Text
    4c1b1937-b330-4172-b6b4-fe7f3bc8ebde: 'Meta Page Description' # Meta Page Description
    5a72f800-8d3a-401e-a06a-58040bae612a: Stats # Stats
    5e9517dd-12e4-432b-8d84-b04f4723109e: href # href
    5ebc446b-1d16-47b3-890a-35c338268fa6: Imprint # Imprint
    6ae3604a-a79b-4d64-9f7c-069256175426: CTA # CTA
    6b177a7b-e7bf-48bb-ae7b-4160f6bf4d7d: 'Course Intro Info Peaker' # Course Intro Info Peaker
    6ef04a00-5ae7-4cb6-a2b7-1d1ad0acf651: Services # Services
    6fd6f5f4-2ae1-451d-9f3a-a377f8123232: 'Course Intro Article Label' # Course Intro Article Label
    7efc5e3b-a65c-4408-a215-896492dd1aea: 'Course Intro Quote Name' # Course Intro Quote Name
    7fe5694e-3563-4eca-9971-e73e8cc0f0f1: 'Services ID' # Services ID
    8ca4ffd7-e0ec-486c-ae72-e40e733bc421: button # button
    8cfa3bff-513c-423a-b99d-8aea13bc9592: 'Course Intro Article Image' # Course Intro Article Image
    8d9fb8fc-aa34-42cb-98bc-97228160016c: 'Investment Advisory' # Investment Advisory
    9b6e4be8-876c-4971-95a7-d952bac89124: text # text
    9b20354d-0990-4f36-bd10-d236944601e3: Intro # Intro
    9ca332d8-ae84-4fd6-a910-86840be2a2ad: 'Course Intro Quote Text ' # Course Intro Quote Text 
    9d822dff-c1c0-4211-933b-31fb7ad99fac: Hero # Hero
    9f90e5bc-9157-4526-8dde-681edb929c58: 'Retirement Solutions' # Retirement Solutions
    010edfe8-bf11-404d-ac0e-d609cb946713: CTA # CTA
    24d6a6c1-e3ba-4502-8202-9046cda01144: 'Stats Counters' # Stats Counters
    47e94b3a-30ca-480e-aade-3be1b448c694: 'Data Privacy' # Data Privacy
    63ab7bb9-d043-4d70-b513-c1bd9d75d685: 'Teaser Image' # Teaser Image
    69f52402-22cf-4960-a42a-b404ccea0405: 'Stats Button Text' # Stats Button Text
    77f88702-2981-4e43-9963-965cd0f6bcc8: 'Course Intro Long Copy Text ' # Course Intro Long Copy Text 
    81f1ea57-8f3f-4a92-aa27-52460033d593: 'Hero Heading' # Hero Heading
    83d2d997-ad1f-49c6-901c-3663f63358f5: 'Course Intro Quote Role' # Course Intro Quote Role
    84babe93-8199-4bb0-8db8-7586bbc5e99c: Intro # Intro
    86baf79e-9a0e-4654-9494-66d604f2a4d4: Heroine # Heroine
    146a4478-2537-438c-acbf-11cd3bf2bfa4: Hero # Hero
    465ad94a-6ff0-4776-aec3-1a8d9c28d177: Start # Start
    505b5f6b-5951-4484-9ced-7f3f61abc5d9: Login # Login
    535b41e8-932f-49eb-80e0-a57aad52a713: Teaser # Teaser
    567b3a46-9655-43df-8e0d-02a52454e459: 'About Us' # About Us
    611a3848-5826-4e32-bb17-992fd9937ba8: 'Hero Button' # Hero Button
    0622be8b-b30f-4d45-8e51-c0449d675572: 'Meta Page Title' # Meta Page Title
    967ce7fc-82b0-4640-b4fc-88a245b7585e: 'Course Intro Info  Button Text' # Course Intro Info  Button Text
    1603d4ed-dff5-40eb-8f99-db85545a375e: Start # Start
    1996da9d-6afd-485e-9520-e734f9bef432: 'Services Long Copy' # Services Long Copy
    2335bc14-e769-484f-9f4f-9dc2f14e9db3: Services # Services
    5797b8b9-3f5f-4ea9-8bd6-80f9e56e761e: 'Retirement Solutions' # Retirement Solutions
    78967eb2-4573-48b8-830b-07fc6954c961: 'Teaser Heading' # Teaser Heading
    01907158-7087-433f-a781-b6f78c024142: 'Hero Image' # Hero Image
    4238344f-04f7-4d53-93f6-bdc74afc27b6: Href # Href
    6384771e-f281-43f1-b837-ba8472992e03: 'Services Label' # Services Label
    06591078-9481-42e1-a081-4b0684eb111b: 'Course Intro Info  List' # Course Intro Info  List
    9981532a-4d9a-4060-bacf-c0c4959b6d85: 'Course Intro Info  Text' # Course Intro Info  Text
    51615717-e499-40ee-93b5-35714cad533e: 'Course Intro Info  Button Href' # Course Intro Info  Button Href
    68473838-5b99-491d-b305-d7d0b6b2c1ac: 'Course Intro Article Text' # Course Intro Article Text
    86474971-bcf9-4931-b7e1-67ca6accab6e: List # List
    a8a54faf-f815-4b38-80ee-c66acca0a063: Contact # Contact
    a81b2519-de8d-404a-bff8-bcc3402ad870: Default # Default
    a5530e38-a5e3-4672-afb8-7890d820c586: Stats # Stats
    ab59ddba-c09b-4532-b5cd-f6592b6d237f: Text # Text
    abb7c8e9-a3e2-4c0d-a2f4-23606f8a06e2: Contact # Contact
    ac664f09-a9af-40d3-a60f-889403d18d91: kr-consulting # kr-consulting
    aea1317d-1e20-4ed7-9ff3-2aa3adc44925: 'Stats Peaker' # Stats Peaker
    af78bb5f-d02a-42d9-b97f-9aa6b4c077fd: 'Stats Button Href' # Stats Button Href
    b577bd63-5d61-4855-bc46-c9b942083cf8: amount # amount
    b645bed4-42c3-4a07-adae-f918e4d05e24: 'Course Intro Long Copy Heading' # Course Intro Long Copy Heading
    b6338b26-4732-4e95-bd2f-d6ce9da766ca: Hero # Hero
    b775433a-4ff9-4a89-8266-7cc268cdd27d: 'Intro Text' # Intro Text
    ba58fc37-be30-4b99-a88d-7f4d9e94e73d: kr-consulting # kr-consulting
    bdc004e6-236b-4444-a1c9-8e8cfbdcc67c: Imprint # Imprint
    be44ff42-29c5-445b-be33-efb43b545cd0: 'CTA Heading' # CTA Heading
    c03fd4f8-9d29-48e8-871a-0640a9b29a06: General # General
    c2f319a5-193f-4bcf-8906-fbc7cf6f6a5d: Teaser # Teaser
    c157b61b-db87-471f-8609-c7f60ecf7283: Login # Login
    cf0c14ba-cc45-4b47-bdf2-24ae9f3fd86a: 'Image Alt Tag' # Image Alt Tag
    cf05b8dd-8dfa-47ae-a86d-e19e315bd668: 'Data Privacy' # Data Privacy
    d6ade586-96dd-4523-903d-924c4fe7df63: 'Course Intro Info Image' # Course Intro Info Image
    d6fab119-06a5-434f-bab0-8836d0bebef0: 'Course Intro' # Course Intro
    d8f9a01c-3729-4a9d-838c-aaae7fae2bfe: 'Course Intro Article Outro' # Course Intro Article Outro
    d823a91c-5e63-4e68-9eb0-93d775259750: 'Services Image' # Services Image
    d2481310-b317-4bb2-8863-d25fdae20952: 'Course Intro' # Course Intro
    dace2c28-14d6-44d9-bdb5-c219839745d7: 'Services Short Copy' # Services Short Copy
    dbd572db-9982-4f04-a380-7ede02769ab3: Intro # Intro
    df5fbac6-796e-4d60-8db8-173325a9d555: CTA # CTA
    dfc00c2f-8e40-41cf-8181-3df7d8cd37ca: 'Teaser Button Text' # Teaser Button Text
    dfed0f48-8e31-47d3-a4f9-bc0c00a21ee0: 'Course Intro' # Course Intro
    e01f2cd6-6f33-4599-ab41-3d7481c412eb: 'Stats Heading' # Stats Heading
    e4e357ab-0179-4c12-a820-364727587b32: Counter # Counter
    e7ce083a-c963-4214-9fa8-31b6c05ec30f: 'Course Intro Article Heading' # Course Intro Article Heading
    e48a7320-f8b9-4ab1-b877-7b9c3bcd9b7a: 'Teaser Button Href' # Teaser Button Href
    e66e9dbe-8ea7-4e6a-9d54-712031a2d2a7: Meta # Meta
    e286f9b7-986e-4d00-a407-41b8c313cfa7: 'Heroine Text' # Heroine Text
    e8438c19-b6ae-4ad5-b06e-8e132c4ebd3c: Button # Button
    ed56c4b6-5401-43d7-931b-7f80f482366b: Text # Text
    eeada128-dc74-4253-8a77-f784c19c2fe7: 'Course Intro Quote Image' # Course Intro Quote Image
    f02756b0-2a21-4a86-a44f-d8b2b9cb67af: Image # Image
    f6c273e6-1de9-44f8-964e-74d5586d58cd: 'Services Heading' # Services Heading
    f9dc201a-1d70-41de-addd-45fd5fafb195: 'Investment Advisory' # Investment Advisory
    f989ecb4-faa8-4859-9890-1f9f818af555: Label # Label
    fb774718-6b6d-4033-8391-c1e5225d7442: 'CTA Button Href' # CTA Button Href
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: kr-consulting
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
